ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - core-js-pure
  - tree-sitter
  - tree-sitter-json
